name: Create Verified Commit

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-verified-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GPG key for signing commits
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_config_global: true

      - name: Set Git identity
        run: |
          git config --global user.name "Sidharth Sharma"
          git config --global user.email "Sidharth.Sharma1@dell.com"

      - name: Create or Modify file
        run: |
          echo "This is a verified commit" > new_file.txt
          git add new_file.txt

      - name: Commit changes with GPG signature
        run: |
          git commit -S -m "Create verified commit"
        
      - name: Push changes
        run: |
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
