# .github/workflows/sign-commit.yml
name: Signed Commit via GitHub Actions Bot

on:
  workflow_dispatch:

jobs:
  signed-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub Actions bot identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make a commit (dummy timestamp)
        run: |
          echo "Timestamp: $(date)" >> changes.txt
          git add changes.txt
          git commit -m "Add timestamp"

      - name: Push commit (automatically signed by GitHub API)
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}  # Fine-grained PAT with 'repo' scope
        run: |
          git push origin HEAD:${{ github.ref_name }}
