name: Create Verified Commits
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  create-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Make changes
        run: |
          echo "Updated: $(date)" > timestamp.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Pre-commit" || echo "No changes to commit"

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: "changes-${{ github.run_id }}"
          commit-message: "chore: automated updates"
          title: "Auto-update files"
          sign-commits: true