# .github/workflows/sign-as-actor.yml
name: Signed Commit as Triggering User

on:
  workflow_dispatch:

jobs:
  commit-as-actor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set author as triggering user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Make a change and commit
        run: |
          echo "Timestamp: $(date)" >> changes.txt
          git add changes.txt
          git commit -m "Add timestamp as ${{ github.actor }}"

      - name: Push commit using GitHub token
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.ref_name }}
