name: Commit and Push Changes

on:
  workflow_dispatch: # allows manual trigger

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }} 
    
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
          gpg_private_key: ${{ secrets.CSM_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.CSM_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_config_global: true

    - name: Make changes
      run: |
        echo "Some new content" >> newfile.txt
        # You can run your own script here instead

    - name: Commit and push changes
      run: |
        git add .
        git commit -m -S "chore: automated changes"
        git push
