name: Commit and Create Pull Request

on:
  workflow_dispatch: # manual trigger

jobs:
  commit_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }} # needed for creating PRs on protected branches

    - name: Make changes
      run: |
        echo "Some new content" >> newfile1.txt
        # Your custom modification commands here

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with: 
        commit-message: "chore: automated changes"
        branch: my-update
        title: "chore: automated changes"
        body: |
          This PR was created automatically by a GitHub Action.
        sign-commits: true
        delete-branch: true
